In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

## Create arrrays using using numpy
## Crat a 1 d array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [7]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1row and 5 column

array([[1, 2, 3, 4, 5]])

In [8]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [10]:
## 2d array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [12]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## idebtity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
## Attributes od numpy array
arr = np.array([[1,2,3,4,5],[6,7,8,9,3]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)
print(arr.itemsize)


[[1 2 3 4 5]
 [6 7 8 9 3]]
(2, 5)
10
int64
2
8


In [ ]:
## Numpy Vectorized Operations

arr1=np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise operation
## Element wise addition
print(arr1 + arr2)

## Element wise subtraction
print(arr1 - arr2)

## Element wise multiplication
print(arr1 * arr2)

## Element wise division
print(arr2 / arr1)


[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [25]:
## Universal functions -> Functions that are applied to the entire array

arr = np.array([1,2,3,4,5,6])

## Square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [34]:
## array slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

print(arr[0][0])
print(arr[2])
print(arr[1:])
print(arr[1:,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[ 9 10 11 12]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]


In [35]:
print(arr[:2,2:])

[[3 4]
 [7 8]]


In [38]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [40]:
## Modify the array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [41]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [50]:
## Statistical concepts- Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# Calculate mean and standard devaition
mean = np.mean(data)
print(mean)
std_dev = np.std(data)
print(std_dev)

# Normalize the data
normalized_data = (data-mean)/std_dev
print("Normalized data : " ,normalized_data)
print(np.std(normalized_data))

3.0
1.4142135623730951
Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
0.9999999999999999


In [52]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.std(data))

5.5
5.5
8.25
2.8722813232690143


In [55]:
## Logical Operations

data = np.array([1,2,3,4,5,6,7,8,9,10])
print(data>5)
print(data[data>5])
print(data[(data>=5) & (data<=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
